---
language: ruby
builder_args: --jobs 7
script: bin/rake test
notifications:
  irc:
    channels:
      - 'chat.freenode.net#bloomberg'
    use_notice: true
    template:
      - "%{message} (%{author}): %{build_url}"
branches:
  only:
    - master
rvm:
  - 2.1
  - 1.9.3
